
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\lovea\Documents\python\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("950x600")
window.configure(bg = "#52DFBD")


canvas = Canvas(
    window,
    bg = "#52DFBD",
    height = 600,
    width = 950,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    44.0,
    45.0,
    901.0,
    561.0,
    fill="#FFFBFB",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    628.0,
    338.0,
    image=image_image_1
)

canvas.create_text(
    108.0,
    333.0,
    anchor="nw",
    text="\nJunte-se a nós e faça parte da nossa comunidade apaixonada por filmes. Comece sua jornada cinematográfica conosco hoje mesmo e descubra o prazer de assistir aos melhores filmes, quando e onde quiser.",
    fill="#0C3027",
    font=("Inter", 13 * -1)
)

canvas.create_text(
    92.0,
    274.0,
    anchor="nw",
    text="O destino certo para encontrar o filme perfeito.",
    fill="#7FF4D8",
    font=("Inter Bold", 20 * -1)
)

canvas.create_text(
    481.0,
    81.0,
    anchor="nw",
    text="Carrinho",
    fill="#56C891",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    230.0,
    82.0,
    anchor="nw",
    text="Inicio",
    fill="#56C891",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    352.0,
    81.0,
    anchor="nw",
    text="Categoria",
    fill="#56C891",
    font=("Inter", 14 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=776.0,
    y=74.0,
    width=84.0,
    height=28.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=192.0,
    y=485.0,
    width=91.0,
    height=29.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    669.0,
    89.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=599.0,
    y=76.0,
    width=140.0,
    height=24.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    142.0,
    102.0,
    image=image_image_2
)
window.resizable(False, False)
window.mainloop()
