
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\lovea\Documents\python\dbproject\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("950x600")
window.configure(bg = "#52DFBD")


canvas = Canvas(
    window,
    bg = "#52DFBD",
    height = 600,
    width = 950,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    5.0,
    469.0,
    610.0,
    fill="#FFFDFD",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    90.0,
    63.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    90.0,
    63.0,
    image=image_image_2
)

canvas.create_rectangle(
    529.0,
    240.0,
    892.0,
    499.0,
    fill="#E6FBF8",
    outline="")

canvas.create_text(
    582.0,
    150.0,
    anchor="nw",
    text="Bem Vindo de Volta!",
    fill="#0E795F",
    font=("Inter Bold", 24 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    710.5,
    322.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#B7EEE0",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=605.0,
    y=307.0,
    width=211.0,
    height=28.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    713.5,
    390.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#B7EEE0",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=608.0,
    y=375.0,
    width=211.0,
    height=28.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=629.0,
    y=434.0,
    width=176.0,
    height=30.0
)

canvas.create_text(
    600.0,
    289.0,
    anchor="nw",
    text="nome",
    fill="#0E795F",
    font=("Inter", 13 * -1)
)

canvas.create_text(
    593.0,
    356.0,
    anchor="nw",
    text="senha",
    fill="#0E795F",
    font=("Inter", 13 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    216.0,
    348.0,
    image=image_image_3
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=697.0,
    y=475.0,
    width=36.0,
    height=12.0
)
window.resizable(False, False)
window.mainloop()
